name: datawhys
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - python=3.7
  - xeus-python
  - jupyterlab=1.2.14
  - ptvsd
  - nodejs
  - plotly=4.8.1
  - pip
  - pandas
  - matplotlib
  - scikit-learn
  - ipympl
  - numpy
  - pip:
    - jupyter-offlinenotebook==0.0.11
