name: datawhys
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - python=3.7
  - xeus-python=0.7.1
  - jupyterlab=1.2.14
  - ptvsd
  - nodejs
  - plotly=4.8.1
  - pip
  - pandas
  - matplotlib
  - scikit-learn
  - ipympl
  - numpy
